### ISSUE TITLE
Parse args.

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#17]
I think a behaviour similar to chromium would be good. That means:

If no instance of rainbow-lollipop is running, open all args as URLs in individual Tracks.

If a instance is running, open new tracks.

That would finally make it possible to set `rainbow-lollipop` as default browser for `xdg-open`

**Comment by grindhold** [comment]
already thought of it, thanks for entering it in the bugtracker :)
this feature is mandatory

**Comment by grindhold** [comment]
done as of 1e4141d

**Comment by lukasepple** [comment]
FUCK YEAH PARTY HARD :tada: :balloon:
