### ISSUE TITLE
reload page feature

### ISSUE THREAD

**Issue by grindhold** [grindhold/rainbow-lollipop#18]
currently, rainbow lollipop has no means to reload the current node.
keep in mind, that the F-keys (F1-F12) are meant to switch between browsermodes.

**Comment by lukasepple** [comment]
C-r is the common keybind for that.

**Comment by grindhold** [comment]
@lukasepple sounds reasonable. it shall be this way.

**Comment by grindhold** [comment]
fixed with a8e103c and 5fbddf8
