### ISSUE TITLE
migrate to ØMQ4

### ISSUE THREAD

**Issue by grindhold** [grindhold/rainbow-lollipop#19]
port the program to libzmq 4

Currently its only compatible with libzmq 2.2.0. arch users seem to have problems, getting that old dependencies.

**Comment by lukasepple** [comment]
What is the situation of libzmq 4 on Debian? As it is a AUR package currently, there's no problem in depending on an AUR package.

**Comment by lukasepple** [comment]
But since ØMQ2 is deprecated ØMQ4 would be the better thing.

**Comment by grindhold** [comment]
@lukasepple there was a guy who heard the talk. he said he couldn't get it to run on arch because of this dependency.
nevertheless it would be a good idea to port to ØMQ4.

**Comment by lukasepple** [comment]
You have to install a special package from the AUR which is called `zeromq2`. I also only found it because @glaxx told me.

**Comment by grindhold** [comment]
done as of 9876f9a
