### ISSUE TITLE
Add other distributions to download page

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#21]
e. g. ArchLinux, NixOS (?)

**Comment by iblech** [comment]
A Nix package would be great. Then one could easily try rainbow-lollipop
even if one's distribution ships an ancient version of libwebkit2gtk
(for instance, Ubuntu Precise). (This affects a friend of mine. He was
hooked since the talk at the nerd night, but was not yet able to install
it.)

**Comment by lukasepple** [comment]
there's already a nix expression available. https://github.com/grindhold/rainbow-lollipop/blob/master/release.nix (fails currently afaik)

**Comment by grindhold** [comment]
yup. it fails since i introduced gettext to the project.
here is the relevant portion of the buildlog:

```
/...-gettext-0.18.3/bin/xgettext: cannot create output file "po/rainbow-lollipop.pot": No such file or directory
make[2]: *** [CMakeFiles/pot] Error 1
make[1]: *** [CMakeFiles/pot.dir/all] Error 2
make: *** [all] Error 2
builder for ‘/...-rainbow-lollipop-0.0.1.drv’ failed with exit code 2
```

the relevant line is CMakeLists.txt:181

this works on my local system but not on the nix-buildsystem.

**Comment by grindhold** [comment]
added instructions for arch nixos and gentoo to downloadpage.
