### ISSUE TITLE
Breaking HistoryTrack by using link on deleted Node

### ISSUE THREAD

**Issue by apothecarius** [grindhold/rainbow-lollipop#24]
Initial Situation: You have a historytrack with at least 2 nodes (the first accessed by URL and the second by a link on the first one) and watch the website of the  newer node

Now using the "Close Branch" functionality on the node that your watching right now leaves the webpage open and you can still follow links. This will create new nodes in the existing HistoryTrack with possibly volatile pointers.

This bug will not occur when you Close the Branch on a root node.

Suggested Fix: Let the webview show the parentnode of the one that was closed.
Keeping the visible node existent but moving it in the HistoryTrack (tree) is also possible, but would violate the continuity of browsing history.

**Comment by grindhold** [comment]
bug was fixed with 6d63a94
