### ISSUE TITLE
Add context menu to links

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#29]
Allow

* Copying of links
* Opening in New Tracks
* Downloading
* …

Just ideas for the future™.

**Comment by lightningblaze** [comment]
I support this idea, as I have been using this browser, and find it annoying when I can't save a cool wallpaper I might find, or save a page souce for some reason (like offline viewing)

**Comment by grindhold** [comment]
i approve

**Comment by grindhold** [comment]
fixed as of 3ffd9b6
