### ISSUE TITLE
compiles only with libzmq-2.2.0 - add cmake check

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#33]
I know it was mentioned in issue:19 that it only works with libzmq-2.2.0, but wouldn't it be possible to add a cmake check for it?

**Comment by PeterHuewe** [comment]
You can pull the fix from here  https://github.com/PeterHuewe/rainbow-lollipop/commit/697ba670b3961e1ea1ea8160aeb237186a0244bc

**Comment by grindhold** [comment]
thanks for taking on the task :+1:
