### ISSUE TITLE
DuckDuckGo Search does not work - tries to access search term as host

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#34]
When typing into the adressbar, the duckduckgo search appears.
![rs1](https://cloud.githubusercontent.com/assets/1458946/6907466/bd458f2e-d736-11e4-8c26-eb390dd87924.png)

If I then press "go"/"los" a blank page shows with the error message:
"Fehler beim Auflösen von »rainbow«: Der Name oder der Dienst ist nicht bekannt"
![rs2](https://cloud.githubusercontent.com/assets/1458946/6907495/ea23bfde-d736-11e4-8737-9eae7bbdaa42.png)

Version 1be9f6794ce9ded25f29918c270348e7e8b05fd5 on x86_64 gentoo system

**Comment by shak-mar** [comment]
You need to click on `rainbow suchen` instead of `los`. If you click on `los`, it tries to visit a website with the domain name `rainbow`.

**Comment by PeterHuewe** [comment]
Ah okay - a bit counter-intuitive though :/ 
Maybe mark as enhancement
Thanks

**Comment by grindhold** [comment]
i already have an idea how solve this issue

**Comment by grindhold** [comment]
i am currently working on said feature. i now redesigned the suggestions section. now it's not that obscure anymore.
