### ISSUE TITLE
Addressbar/"History" vanishes on new pages

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#35]
When I enter a url into the addressbar, the new page opens, but unfortunately the addressbar vanishes, as well as the 'history' bubbles.
If I then close the browser and reopen it and restore the session the both appear correct.

Restored session:
![rl1](https://cloud.githubusercontent.com/assets/1458946/6907539/5870bd7a-d737-11e4-97ce-fa650a8a32d4.png)

After entering http://google.de
![rl2](https://cloud.githubusercontent.com/assets/1458946/6907567/a33e750e-d737-11e4-91ed-29a663366182.png)

Version: 1be9f6794ce9ded25f29918c270348e7e8b05fd5 on x86_64 gentoo

**Comment by grindhold** [comment]
you can retrieve them with the TAB-key on your keyboard. i should really document that :]

**Comment by grindhold** [comment]
haven't seen this one in a long while now. i think #50 should've fixed it anyway. please reopen with further information if it happens again.
