### ISSUE TITLE
History forgets to include search terms

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#37]
Hi,
when I use e.g. google for searching something and click on a search result,
press tab to get the history pane back and click on the parent (i.e. google) the search results are gone. (and I have to remember what I searched for)

**Comment by lightningblaze** [comment]
This same issue is with youtube, even opening a whole new video does not create more marks on the track the page is on, so opening youtube in a track and spending an hour on many videos only has 1 page on the track.

**Comment by lukasepple** [comment]
The Problem (with youtube) seems to be, that they catch links and load the content using JS.

**Comment by grindhold** [comment]
maybe we can counter this by using webkits BackForwardList. This should record JS-caused url-changes, too.

**Comment by lukasepple** [comment]
There must be a way to do so, other browsers do that, too. :)

**Comment by grindhold** [comment]
fixed as of 1a8bea3

**Comment by lukasepple** [comment]
Yay!
