### ISSUE TITLE
Crashes On Youtube

### ISSUE THREAD

**Issue by lightningblaze** [grindhold/rainbow-lollipop#38]
I opened youtube to listen to music, it loaded for a second or two, then the whole browser just randomly closed. I started it back up with a new session, opened youtube again, and the same thing happened. No other sites seem to have this issue for me, atleast from what ive been on.

**Comment by lightningblaze** [comment]
Also, I should add I do NOT have adobe flash plugin, so #23 should not be the issue, as it leaves no logs of a crash either.

**Comment by grindhold** [comment]
do you have  any other flashplugin e.g. gnash? or are you using the html5 player?

**Comment by lightningblaze** [comment]
The issue randomly stopped happening, and no I have neither, but it works now so I dont know...

**Comment by grindhold** [comment]
i'll close this. reopen if there is any further information on the problem
