### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#39]
Hi,

unfortunately downloads are not working correctly yet.
Steps to reproduce:
goto kernel.org
click on 'latest stable kernel', nothing happens (except an entry in the trackbar)

**Comment by grindhold** [comment]
yup. this is due to bad mimetype checking. the browser does not know what to do with e.g. a .tar.gz right now. i think some issue mentioned that before

**Comment by grindhold** [comment]
note to myself: seems to work since we use WebKit.BackForwardList to track the calls. What's still broken is:
  * The position at which downloadnodes get inserted
  * The progress display on the downloadnode

**Comment by grindhold** [comment]
fixed as of f874e02
