### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by lightningblaze** [grindhold/rainbow-lollipop#41]
Most of the pages I go on have an issue with staying logged in. This happens even If I log in, check the "Keep me logged in" box, or whatever the page has, close the browser, and open it again with "Restore Session". This can get slightly annoying having to log in to everything over and over again. 
(sorry ive offloaded so many issues within my few days of using this browser, im good at breaking things apparently)

**Comment by grindhold** [comment]
yep, that is an issue indeed. don't hesitate dropping issues here. otherwise they will be forgotten.

**Comment by grindhold** [comment]
fixed as of 768822b
