### ISSUE TITLE
Add Search Keywords

### ISSUE THREAD

**Issue by PeterHuewe** [grindhold/rainbow-lollipop#45]
One feature I really really really like e.g. of firefox is the possibility to add 'search keywords'.

i.e. if I type
'wi mykeyword' it automatically performs a search on wikipedia as
https://de.wikipedia.org/wiki/Spezial:Suche?search=mykeyword

In Firefox it is possible to select an arbitrary (GET) input form field and select it as 'search keyword'.

**Comment by grindhold** [comment]
you did it :)
