### ISSUE TITLE
Pressing Tab with no tracks open leads to freeze

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#50]
Browser freezes. Browser does only show white space. The WM is not able to render the Window again after switching workspaces. Unable to close the Window via WM's shortcut.

Reproduce: Press TAB without having a track open.

**Comment by PeterHuewe** [comment]
Nice one - I can reproduce it here.

**Comment by PeterHuewe** [comment]
#0  0x00007fffefcdcb3d in poll () from /lib64/libc.so.6
#1  0x00007fffeffb0304 in ?? () from /usr/lib64/libzmq.so.1
#2  0x00007fffeffa787e in ?? () from /usr/lib64/libzmq.so.1
#3  0x00007fffeffb125e in ?? () from /usr/lib64/libzmq.so.1
#4  0x00007fffeffb1600 in ?? () from /usr/lib64/libzmq.so.1
#5  0x0000000000443ffe in rainbow_lollipop_zmq_vent_needs_direct_input_co (_data_=0x1fc77f0) at /fast/rainbow-lollipop/src/ipc.vala:115
#6  0x0000000000443664 in rainbow_lollipop_zmq_vent_needs_direct_input (w=0x26023b0, 
    cb=0x41a8a3 <_rainbow_lollipop_application_do_key_press_event_rainbow_lollipop_ipc_callback>, cb_target=0x6ca290, e=0x20c7970, _callback_=0x0, 
    _user_data_=0x0) at /fast/rainbow-lollipop/src/ipc.vala:81
#7  0x00000000004169f4 in rainbow_lollipop_track_web_view_needs_direct_input_co (_data_=0x201fa40) at /fast/rainbow-lollipop/src/alaia.vala:73
#8  0x00000000004168b8 in rainbow_lollipop_track_web_view_needs_direct_input (self=0x26023b0, 
    cb=0x41a8a3 <_rainbow_lollipop_application_do_key_press_event_rainbow_lollipop_ipc_callback>, cb_target=0x6ca290, e=0x2606730, _callback_=0x0, 
    _user_data_=0x0) at /fast/rainbow-lollipop/src/alaia.vala:50
#9  0x000000000041ad05 in rainbow_lollipop_application_preprocess_key_press_event (self=0x6ca290, e=0x2606730) at /fast/rainbow-lollipop/src/alaia.vala:460
#10 0x00000000004176a9 in _rainbow_lollipop_application_preprocess_key_press_event_gtk_widget_key_press_event (_sender=0x1f0c310, event=0x2606730, 
    self=0x6ca290) at alaia.c:1051
#11 0x00007ffff70e540c in ?? () from /usr/lib64/libgtk-3.so.0
#12 0x00007ffff58f41b8 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff590531d in ?? () from /usr/lib64/libgobject-2.0.so.0
#14 0x00007ffff590ccb8 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#15 0x00007ffff590d2aa in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#16 0x00007ffff720b87c in ?? () from /usr/lib64/libgtk-3.so.0
#17 0x00007ffff70e30b8 in ?? () from /usr/lib64/libgtk-3.so.0
#18 0x00007ffff70e4a67 in gtk_main_do_event () from /usr/lib64/libgtk-3.so.0
#19 0x00007ffff6cb8222 in ?? () from /usr/lib64/libgdk-3.so.0
#20 0x00007ffff7aed754 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#21 0x00007ffff7aed998 in ?? () from /usr/lib64/libglib-2.0.so.0
#22 0x00007ffff7aedc5a in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#23 0x00007ffff70e3d95 in gtk_main () from /usr/lib64/libgtk-3.so.0
#24 0x000000000041c5fe in rainbow_lollipop_application_main (args=0x7fffffffd798, args_length1=1) at /fast/rainbow-lollipop/src/alaia.vala:603
#25 0x000000000041c64d in main (argc=1, argv=0x7fffffffd798) at /fast/rainbow-lollipop/src/alaia.vala:593

**Comment by grindhold** [comment]
fixed as of 8e7c792

**Comment by lukasepple** [comment]
Confirmed :D
