### ISSUE TITLE
Recognize following a link to the last page in the current branch history as going back in browsing history

### ISSUE THREAD

**Issue by lukasepple** [grindhold/rainbow-lollipop#56]
E. g. I surf on github.com, follow a link somewhere but instead of using the Track view, I click the Github logo to return to github.com, This would fix many obscure Track Trees.

**Comment by grindhold** [comment]
done as of 7c89e34

maybe we should think about making this behaviour recursive in the future.
simplified: if i find the called url in _any_ parent of the current_node, i will choose that node as new current_node instead of creating a new one
