### ISSUE TITLE
Build fails since 34a0713

### ISSUE THREAD

**Issue by shak-mar** [grindhold/rainbow-lollipop#79]
I am working on a fix for `release.nix`, as it fails to build. The commit I pushed to my fork (https://github.com/shak-mar/rainbow-lollipop/commit/5f3cc6c00752981067404866eb253264408014af) seems to work pretty well. But when I try to rebase onto any commit from 34a0713 on, the build fails with the following error:
```
…/src/trackwebview.vala:89.42-89.62: error: The name `is_playing_audio' does not exist in the context of `RainbowLollipop.TrackWebView'
            this.track.set_audio_playing(this.is_playing_audio);
```

**Comment by grindhold** [comment]
it's possible that you have outdated VAPIs that ship with your vala compiler. the vapis supplied by valac 0.28.x should include the required methods and properties.

**Comment by shak-mar** [comment]
Nice, that fixed the problem.
